### ISSUE TITLE
Button 'gui.select_schematic.path' crasht Spiel

### ISSUE THREAD

**Issue by jgh07** [M-Marvin/MCMOD-HoloStructures#2]
Durch das Betätigen des Knopfes mit der Aufschrift "gui.select_schematic.path" stürzt bei mir das Spiel ab. Die Exception-Nachricht lautet wie folgt:

````
java.lang.NullPointerException: Tesselating Holoblock model
	at de.holostructure.util.SchematicStruckture.renderBlockObjects(SchematicStruckture.java:230) ~[?:1.0] {re:classloading}
	at de.holostructure.util.SchematicStruckture.render(SchematicStruckture.java:209) ~[?:1.0] {re:classloading}
	at de.holostructure.util.Events.onRenderEvent(Events.java:30) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_7_Events_onRenderEvent_RenderWorldLastEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2531/2043007629.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:154) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:723) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1027) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.14.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$439/935722070.call(Unknown Source) [forge-1.16.5-36.0.14.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
````
Sieht mMn nach einer selbst geworfenen Exception (keine Ahnung was "tesselating model" hier heißen soll). Habe die Mod lange nicht mehr benutzt, ich wollte einen Dialog wo ich die schematic auswählen kann, keine Ahnung ob das der richtige Button ist. xD

**Comment by jgh07** [comment]
Ok, ich weiß jetzt wozu der Button da ist (hab jetzt im Forum bei der Anleitung geschaut, jetzt ist es selbsterklärend), aber die Beschriftungen scheinen ja trotzdem nicht so gewollt zu sein.

**Comment by M-Marvin** [comment]
Hm, es scheint das so als ob deine Schematic nicht geladen werden konnte, die List von Blöcken der geladenen Schematic ist null (also nicht vorhanden) daher ist es beim rendern abgestürzt ("NullPointerException").

Kannst du mir mal die ganze Log und eventuell die entsprechende Schematic senden ?

Und hast du die Sprache eventuell auf was anderes als Deutsch gestellt? das erklärt dann das da kein richtiger Text steht.
Ich hab noch keine Übersetzung gemacht, hab ich bis eben auch gar nicht mehr dran gedacht, weil ich immer auf Deutsch spiele.

**Comment by M-Marvin** [comment]
Und "Tesselating Holoblock model" bedeutet so viel wie "Rendern des Hologramm-Blocks"

**Comment by jgh07** [comment]
Ja, es lag an der Minecraftsprache. Habe es jetzt eh herausgefunden (hatte das Textfeld leergelassen, weil ich nicht wusste was der Button macht). Ich fände es in diesem Fall aber besser, wenn irgend eine Fehlermeldung angezeigt wird oder einfach nichts passiert, anstatt dass das Spiel abstürzt. Aber da ich es jetzt eh weiß, schließe ich das Issue mal.
